name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: create GitHub release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
